"""grille tarifaire baremes degressifs

Revision ID: 1f151d0e24cf
Revises: 43c4570f716b
Create Date: 2026-09-06 07:34:12.985041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f151d0e24cf'
down_revision: Union[str, None] = '43c4570f716b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    type_partenaire_enum = sa.Enum('BANQUE', 'IMF', name='type_partenaire')
    type_partenaire_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        'grilles_tarifaires',
        sa.Column('taux_total_minimum', sa.Numeric(precision=6, scale=4), nullable=False, server_default='0.023'),
    )
    op.add_column(
        'grilles_tarifaires',
        sa.Column('taux_total_maximum', sa.Numeric(precision=6, scale=4), nullable=False, server_default='0.03'),
    )
    op.add_column(
        'grilles_tarifaires',
        sa.Column('proportion_cedra', sa.Numeric(precision=5, scale=4), nullable=False, server_default='0.3333'),
    )
    op.add_column(
        'grilles_tarifaires',
        sa.Column('proportion_partenaire', sa.Numeric(precision=5, scale=4), nullable=False, server_default='0.6667'),
    )
    op.add_column(
        'grilles_tarifaires',
        sa.Column('duree_maximum_jours', sa.Integer(), nullable=False, server_default='90'),
    )
    op.add_column(
        'grilles_tarifaires',
        sa.Column('type_partenaire', type_partenaire_enum, nullable=False, server_default='BANQUE'),
    )
    op.alter_column('grilles_tarifaires', 'duree_minimum_jours', server_default='60')
    op.alter_column('grilles_tarifaires', 'taux_avance', server_default='0.80')
    op.alter_column('grilles_tarifaires', 'plafond_montant',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.drop_column('grilles_tarifaires', 'repartition_plateforme')
    op.drop_column('grilles_tarifaires', 'repartition_partenaire')
    op.drop_column('grilles_tarifaires', 'pourcentage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grilles_tarifaires', sa.Column('pourcentage', sa.NUMERIC(precision=6, scale=4), autoincrement=False, nullable=False))
    op.add_column('grilles_tarifaires', sa.Column('repartition_partenaire', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False))
    op.add_column('grilles_tarifaires', sa.Column('repartition_plateforme', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False))
    op.alter_column('grilles_tarifaires', 'plafond_montant',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.drop_column('grilles_tarifaires', 'type_partenaire')
    op.drop_column('grilles_tarifaires', 'duree_maximum_jours')
    op.drop_column('grilles_tarifaires', 'proportion_partenaire')
    op.drop_column('grilles_tarifaires', 'proportion_cedra')
    op.drop_column('grilles_tarifaires', 'taux_total_maximum')
    op.drop_column('grilles_tarifaires', 'taux_total_minimum')
    sa.Enum(name='type_partenaire').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
