"""relation pme donneur ordre et jeton rejoindre entreprise

Revision ID: 2328db09ae96
Revises: aaeeb7b1336c
Create Date: 2026-09-05 19:28:14.165954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2328db09ae96'
down_revision: Union[str, None] = 'aaeeb7b1336c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relations_pme_donneur_ordre',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pme_id', sa.UUID(), nullable=False),
    sa.Column('donneur_ordre_id', sa.UUID(), nullable=False),
    sa.Column('statut', sa.Enum('PILOTE', 'CONVENTION_SIGNEE', name='statut_relation'), nullable=False),
    sa.Column('factures_pilote_max', sa.Integer(), nullable=False),
    sa.Column('factures_pilote_utilisees', sa.Integer(), nullable=False),
    sa.Column('date_debut_relation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donneur_ordre_id'], ['entreprises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pme_id'], ['entreprises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pme_id', 'donneur_ordre_id', name='uq_relation_pme_donneur_ordre')
    )
    op.create_table('validateurs_relation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('relation_id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('date_affectation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['relation_id'], ['relations_pme_donneur_ordre.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relation_id', 'utilisateur_id', name='uq_validateur_relation')
    )
    op.add_column('entreprises', sa.Column('token_invitation_initiale', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'entreprises', ['token_invitation_initiale'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entreprises', type_='unique')
    op.drop_column('entreprises', 'token_invitation_initiale')
    op.drop_table('validateurs_relation')
    op.drop_table('relations_pme_donneur_ordre')
    # ### end Alembic commands ###
