"""enveloppe partenaire et garantie avance

Revision ID: 26d971ffec05
Revises: 2328db09ae96
Create Date: 2026-09-05 20:00:50.158861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26d971ffec05'
down_revision: Union[str, None] = '2328db09ae96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enveloppes_partenaire',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partenaire_financier_id', sa.UUID(), nullable=False),
    sa.Column('montant_total_alloue', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('date_maj', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partenaire_financier_id'], ['entreprises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partenaire_financier_id')
    )
    op.add_column(
        'avances',
        sa.Column('garantie_detenue_avant_financement', sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('avances', 'garantie_detenue_avant_financement')
    op.drop_table('enveloppes_partenaire')
    # ### end Alembic commands ###
