"""initial schema

Revision ID: 2c2dc410e984
Revises: 
Create Date: 2026-08-23 16:40:00.746348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c2dc410e984'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entreprises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('PME', 'GRANDE_ENTREPRISE', 'PARTENAIRE_FINANCIER', name='type_entreprise'), nullable=False),
    sa.Column('raison_sociale', sa.String(length=255), nullable=False),
    sa.Column('ninea', sa.String(length=50), nullable=False),
    sa.Column('rccm', sa.String(length=50), nullable=False),
    sa.Column('statut_kyc', sa.Enum('EN_ATTENTE', 'VALIDE', 'REJETE', name='statut_kyc'), nullable=False),
    sa.Column('secteur_activite', sa.String(length=255), nullable=False),
    sa.Column('chiffre_affaires', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('date_creation', sa.Date(), nullable=False),
    sa.Column('contact_telephone', sa.String(length=30), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('kyc_document_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grilles_tarifaires',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('pourcentage', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('plafond_montant', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('duree_minimum_jours', sa.Integer(), nullable=False),
    sa.Column('taux_avance', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('repartition_partenaire', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('repartition_plateforme', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('date_debut_validite', sa.Date(), nullable=False),
    sa.Column('date_fin_validite', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero_facture', sa.String(length=100), nullable=False),
    sa.Column('pme_id', sa.UUID(), nullable=False),
    sa.Column('donneur_ordre_id', sa.UUID(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('devise', sa.String(length=10), nullable=False),
    sa.Column('date_emission', sa.Date(), nullable=False),
    sa.Column('date_echeance', sa.Date(), nullable=False),
    sa.Column('duree_jours', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Enum('EMISE', 'VALIDEE', 'VALIDATION_COMPLEMENTAIRE_REQUISE', 'AVANCE_DEMANDEE', 'AVANCE_VERSEE', 'SOLDEE', 'EN_RETARD', 'LITIGE', 'REJETEE', name='statut_facture'), nullable=False),
    sa.Column('piece_justificative_url', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('source_creation', sa.Enum('SAISIE_MANUELLE', 'IMPORT_FICHIER', name='source_creation_facture'), nullable=False),
    sa.Column('date_derniere_maj', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donneur_ordre_id'], ['entreprises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pme_id'], ['entreprises.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factures_numero_facture'), 'factures', ['numero_facture'], unique=False)
    op.create_table('limites_credit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partenaire_financier_id', sa.UUID(), nullable=False),
    sa.Column('entreprise_cible_id', sa.UUID(), nullable=False),
    sa.Column('type_limite', sa.Enum('ACHETEUR', 'FOURNISSEUR', name='type_limite'), nullable=False),
    sa.Column('montant_plafond', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('montant_utilise', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_cible_id'], ['entreprises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partenaire_financier_id'], ['entreprises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores_donneur_ordre',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entreprise_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('facteurs_positifs', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('facteurs_negatifs', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('modele_version', sa.String(length=50), nullable=False),
    sa.Column('date_calcul', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('calculee_par', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entreprise_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('GESTIONNAIRE_PME', 'VALIDEUR_ENTREPRISE', 'AGENT_FINANCIER', 'ADMIN_PLATEFORME', 'SUPER_ADMIN', 'SUPPORT', name='role_utilisateur'), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('mot_de_passe_hash', sa.String(length=512), nullable=False),
    sa.Column('mfa_actif', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('derniere_connexion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('compte_actif', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateurs_telephone'), 'utilisateurs', ['telephone'], unique=True)
    op.create_table('avances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facture_id', sa.UUID(), nullable=False),
    sa.Column('partenaire_financier_id', sa.UUID(), nullable=False),
    sa.Column('grille_tarifaire_id', sa.UUID(), nullable=False),
    sa.Column('montant_avance_initial', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('frais_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('montant_solde_du', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('part_partenaire', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('part_plateforme', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taeg_annualise', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('date_versement_initial', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_versement_solde', sa.DateTime(timezone=True), nullable=True),
    sa.Column('statut', sa.Enum('EN_ATTENTE_VALIDATION', 'AVANCE_VERSEE', 'SOLDEE', 'EN_DEFAUT', 'REJETEE', name='statut_avance'), nullable=False),
    sa.Column('methode_versement', sa.Enum('WAVE', 'VIREMENT_BANCAIRE', name='methode_versement'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grille_tarifaire_id'], ['grilles_tarifaires.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partenaire_financier_id'], ['entreprises.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facture_id')
    )
    op.create_table('journal_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entite_type', sa.String(length=100), nullable=False),
    sa.Column('entite_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=True),
    sa.Column('horodatage', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valeur_avant', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('valeur_apres', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_audit_entite_id'), 'journal_audit', ['entite_id'], unique=False)
    op.create_index(op.f('ix_journal_audit_entite_type'), 'journal_audit', ['entite_type'], unique=False)
    op.create_table('messages_facture',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facture_id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('contenu', sa.String(length=4000), nullable=False),
    sa.Column('date_envoi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lu', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_table('tickets_support',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entreprise_id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('sujet', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=False),
    sa.Column('statut', sa.Enum('OUVERT', 'EN_COURS', 'RESOLU', 'FERME', name='statut_ticket'), nullable=False),
    sa.Column('priorite', sa.String(length=20), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_resolution', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validations_facture',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facture_id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('ordre_validation', sa.Integer(), nullable=False),
    sa.Column('date_validation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('commentaire', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facture_id', 'ordre_validation', name='uq_validation_facture_ordre')
    )
    op.create_table('remboursements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('avance_id', sa.UUID(), nullable=False),
    sa.Column('montant_recu', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('date_reception', sa.Date(), nullable=False),
    sa.Column('source_entreprise_id', sa.UUID(), nullable=False),
    sa.Column('statut_rapprochement', sa.Enum('EN_ATTENTE', 'RAPPROCHE', 'ECART_DETECTE', name='statut_rapprochement'), nullable=False),
    sa.Column('declenche_versement_solde', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avance_id'], ['avances.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_entreprise_id'], ['entreprises.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remboursements')
    op.drop_table('validations_facture')
    op.drop_table('tickets_support')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('messages_facture')
    op.drop_index(op.f('ix_journal_audit_entite_type'), table_name='journal_audit')
    op.drop_index(op.f('ix_journal_audit_entite_id'), table_name='journal_audit')
    op.drop_table('journal_audit')
    op.drop_table('avances')
    op.drop_index(op.f('ix_utilisateurs_telephone'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    op.drop_table('scores_donneur_ordre')
    op.drop_table('limites_credit')
    op.drop_index(op.f('ix_factures_numero_facture'), table_name='factures')
    op.drop_table('factures')
    op.drop_table('grilles_tarifaires')
    op.drop_table('entreprises')
    # ### end Alembic commands ###
