"""conformite facture montant ht tva ttc

Revision ID: 3e8158c52573
Revises: 5de4b90a353a
Create Date: 2026-08-24 15:43:46.735197

Hand-adjusted (not left as raw autogenerate output): the new montant_ht/montant_tva/
montant_ttc columns are NOT NULL, so on a database with existing rows they need a
backfill *between* being added and being constrained, not added NOT NULL directly (the
autogenerated version would fail on any non-empty factures table). montant_ttc takes over
the old `montant` column's value ; montant_ht/montant_tva are derived from it using the
18% default VAT rate, on the assumption that pre-existing rows predate the conformity
feature and were never TVA-decomposed. Also adds the new `REJETEE_CONFORMITE` label to
the statut_facture enum (autogenerate does not detect Postgres enum value additions).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e8158c52573'
down_revision: Union[str, None] = '5de4b90a353a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE statut_facture ADD VALUE IF NOT EXISTS 'REJETEE_CONFORMITE'")

    op.add_column('factures', sa.Column('montant_ht', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column(
        'factures',
        sa.Column('taux_tva', sa.Numeric(precision=5, scale=4), nullable=False, server_default='0.18'),
    )
    op.add_column('factures', sa.Column('montant_tva', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('factures', sa.Column('montant_ttc', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('factures', sa.Column('ninea_emetteur_extrait', sa.String(length=20), nullable=True))
    op.add_column('factures', sa.Column('code_validation_dgid', sa.String(length=255), nullable=True))
    op.add_column(
        'factures',
        sa.Column('conformite_verifiee', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'factures', sa.Column('motifs_rejet_conformite', postgresql.JSON(astext_type=sa.Text()), nullable=True)
    )

    # Backfill : montant_ttc reprend l'ancien montant ; HT/TVA sont derives au taux par
    # defaut (18%) faute de decomposition disponible sur les lignes anterieures a cette
    # fonctionnalite.
    op.execute(
        """
        UPDATE factures
        SET montant_ttc = montant,
            montant_ht = ROUND(montant / 1.18, 2),
            montant_tva = montant - ROUND(montant / 1.18, 2)
        """
    )

    op.alter_column('factures', 'montant_ht', nullable=False)
    op.alter_column('factures', 'montant_tva', nullable=False)
    op.alter_column('factures', 'montant_ttc', nullable=False)
    op.alter_column('factures', 'taux_tva', server_default=None)
    op.alter_column('factures', 'conformite_verifiee', server_default=None)

    op.drop_column('factures', 'montant')


def downgrade() -> None:
    op.add_column('factures', sa.Column('montant', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.execute("UPDATE factures SET montant = montant_ttc")
    op.alter_column('factures', 'montant', nullable=False)

    op.drop_column('factures', 'motifs_rejet_conformite')
    op.drop_column('factures', 'conformite_verifiee')
    op.drop_column('factures', 'code_validation_dgid')
    op.drop_column('factures', 'ninea_emetteur_extrait')
    op.drop_column('factures', 'montant_ttc')
    op.drop_column('factures', 'montant_tva')
    op.drop_column('factures', 'taux_tva')
    op.drop_column('factures', 'montant_ht')
    # Note : Postgres ne permet pas de retirer une valeur d'enum ; REJETEE_CONFORMITE
    # reste dans le type statut_facture apres ce downgrade (inoffensif : simplement inutilisee).
