"""conventions domiciliation et comptes dedies

Revision ID: 43c4570f716b
Revises: 26d971ffec05
Create Date: 2026-09-05 23:52:35.057442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43c4570f716b'
down_revision: Union[str, None] = '26d971ffec05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comptes_dedies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('relation_id', sa.UUID(), nullable=False),
    sa.Column('numero_compte', sa.String(length=64), nullable=False),
    sa.Column('banque_teneur', sa.String(length=255), nullable=False),
    sa.Column('statut', sa.Enum('EN_OUVERTURE', 'ACTIF', 'CLOTURE', name='statut_compte_dedie'), nullable=False),
    sa.Column('date_ouverture', sa.Date(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['relation_id'], ['relations_pme_donneur_ordre.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relation_id')
    )
    op.create_table('conventions_domiciliation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('relation_id', sa.UUID(), nullable=False),
    sa.Column('compte_dedie_id', sa.UUID(), nullable=True),
    sa.Column('signature_pme', sa.Boolean(), nullable=False),
    sa.Column('signature_donneur_ordre', sa.Boolean(), nullable=False),
    sa.Column('signature_partenaire', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['compte_dedie_id'], ['comptes_dedies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['relation_id'], ['relations_pme_donneur_ordre.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conventions_domiciliation')
    op.drop_table('comptes_dedies')
    # ### end Alembic commands ###
