"""role enum overhaul: admin membre_pme validateur_1 validateur_2

Revision ID: 85e01bbb0b02
Revises: b5446c3e849e
Create Date: 2026-08-23 17:33:28.533055

Hand-written (not autogenerated): Alembic's autogenerate does not reliably diff the
member set of an existing Postgres ENUM type, so this migration explicitly renames
role_utilisateur's old type out of the way, creates the new 5-value type, and casts the
column across with an explicit mapping.

Two things happen here, not just a rename:

1. The OLD enum's labels stored in Postgres are the Python enum *member names*
   ('GESTIONNAIRE_PME', 'VALIDEUR_ENTREPRISE', ...) because SQLAlchemy's Enum type
   defaults to `.name`, not `.value`, when no `values_callable` is given - which is what
   app.models.utilisateur.Utilisateur.role used until now. The NEW enum switches to
   `values_callable` so Postgres stores the lowercase `.value` strings instead
   ('admin', 'membre_pme', ...), matching what the JWT "role" claim, the API responses,
   and the frontend have used as the wire format all along. So this migration also fixes
   that DB/API casing mismatch for this column, in addition to the role rename.

2. Role mapping:

    GESTIONNAIRE_PME   -> membre_pme  (unambiguous, same PME-side single role)
    AGENT_FINANCIER    -> agent_financier (unchanged)
    ADMIN_PLATEFORME   -> admin        (3 old internal roles collapse into the new
    SUPER_ADMIN        -> admin         single 'admin' role, which now has total
    SUPPORT            -> admin         access - no ambiguity here)
    VALIDEUR_ENTREPRISE -> REFUSED (see below)

VALIDEUR_ENTREPRISE has no safe automatic mapping: the new model splits that single role
into validateur_1 / validateur_2, and guessing which one a given account should become
would silently misassign real validation authority on a donneur d'ordre's invoices. If any
such rows are found, this migration aborts loudly instead of guessing - reassign them by
hand (via the admin panel / a manual UPDATE) and rerun.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '85e01bbb0b02'
down_revision: Union[str, None] = 'b5446c3e849e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_OLD_VALUES = (
    "GESTIONNAIRE_PME",
    "VALIDEUR_ENTREPRISE",
    "AGENT_FINANCIER",
    "ADMIN_PLATEFORME",
    "SUPER_ADMIN",
    "SUPPORT",
)
_NEW_VALUES = ("admin", "membre_pme", "validateur_1", "validateur_2", "agent_financier")


def upgrade() -> None:
    conn = op.get_bind()

    orphaned = conn.execute(
        sa.text("SELECT id, telephone FROM utilisateurs WHERE role = 'VALIDEUR_ENTREPRISE'")
    ).fetchall()
    if orphaned:
        details = ", ".join(f"{row.id} ({row.telephone})" for row in orphaned)
        raise RuntimeError(
            "Migration interrompue : des utilisateurs ont encore le role "
            "'VALIDEUR_ENTREPRISE', qui n'existe plus dans le nouvel enum "
            "(remplace par validateur_1 / validateur_2). Reassignez-les manuellement "
            "(UPDATE utilisateurs SET role = 'VALIDATEUR_1' ou 'VALIDATEUR_2' WHERE id = "
            "... -- avant le cast, donc avec les anciens labels majuscules) puis "
            "relancez cette migration. Comptes concernes : " + details
        )

    op.execute("ALTER TYPE role_utilisateur RENAME TO role_utilisateur_old")
    op.execute("CREATE TYPE role_utilisateur AS ENUM " + str(_NEW_VALUES))
    op.execute(
        """
        ALTER TABLE utilisateurs
        ALTER COLUMN role TYPE role_utilisateur
        USING (
            CASE role::text
                WHEN 'GESTIONNAIRE_PME' THEN 'membre_pme'
                WHEN 'AGENT_FINANCIER' THEN 'agent_financier'
                WHEN 'ADMIN_PLATEFORME' THEN 'admin'
                WHEN 'SUPER_ADMIN' THEN 'admin'
                WHEN 'SUPPORT' THEN 'admin'
                ELSE role::text
            END
        )::role_utilisateur
        """
    )
    op.execute("DROP TYPE role_utilisateur_old")


def downgrade() -> None:
    op.execute("ALTER TYPE role_utilisateur RENAME TO role_utilisateur_new")
    op.execute("CREATE TYPE role_utilisateur AS ENUM " + str(_OLD_VALUES))
    op.execute(
        """
        ALTER TABLE utilisateurs
        ALTER COLUMN role TYPE role_utilisateur
        USING (
            CASE role::text
                WHEN 'membre_pme' THEN 'GESTIONNAIRE_PME'
                WHEN 'admin' THEN 'ADMIN_PLATEFORME'
                WHEN 'validateur_1' THEN 'VALIDEUR_ENTREPRISE'
                WHEN 'validateur_2' THEN 'VALIDEUR_ENTREPRISE'
                WHEN 'agent_financier' THEN 'AGENT_FINANCIER'
                ELSE role::text
            END
        )::role_utilisateur
        """
    )
    op.execute("DROP TYPE role_utilisateur_new")
