"""doublons et litiges

Revision ID: 92ee87d3254a
Revises: eb6cbea0e3be
Create Date: 2026-09-05 18:35:22.411400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '92ee87d3254a'
down_revision: Union[str, None] = 'eb6cbea0e3be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('litiges_dossiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facture_id', sa.UUID(), nullable=False),
    sa.Column('cause', sa.Enum('CHEQUE_SANS_PROVISION', 'CONTESTATION_ACHETEUR', 'ECART_REMBOURSEMENT', 'AUTRE', name='cause_litige'), nullable=False),
    sa.Column('montant_en_jeu', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('statut', sa.Enum('OUVERT', 'EN_COURS', 'RESOLU', name='statut_litige'), nullable=False),
    sa.Column('statut_facture_avant', postgresql.ENUM('BROUILLON', 'EMISE', 'VALIDEE', 'VALIDATION_COMPLEMENTAIRE_REQUISE', 'AVANCE_DEMANDEE', 'AVANCE_VERSEE', 'SOLDEE', 'EN_RETARD', 'LITIGE', 'REJETEE', 'REJETEE_CONFORMITE', name='statut_facture', create_type=False), nullable=False),
    sa.Column('ouvert_par_id', sa.UUID(), nullable=True),
    sa.Column('derniere_action', sa.String(length=50), nullable=True),
    sa.Column('resolution_note', sa.String(length=2000), nullable=True),
    sa.Column('ouvert_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolu_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ouvert_par_id'], ['utilisateurs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_litiges_dossiers_facture_id'), 'litiges_dossiers', ['facture_id'], unique=False)
    # op.add_column() n'emet pas lui-meme de CREATE TYPE pour un Enum Postgres (contrairement
    # a la creation de table) : il faut le faire explicitement avant.
    postgresql.ENUM('PRE_INSCRITE', 'ACTIVE', name='statut_fiche').create(op.get_bind(), checkfirst=True)
    op.add_column(
        'entreprises',
        sa.Column(
            'statut_fiche',
            postgresql.ENUM('PRE_INSCRITE', 'ACTIVE', name='statut_fiche', create_type=False),
            server_default='ACTIVE',
            nullable=False,
        ),
    )
    op.add_column('entreprises', sa.Column('cree_par_entreprise_id', sa.UUID(), nullable=True))
    op.add_column('entreprises', sa.Column('actif', sa.Boolean(), server_default=sa.true(), nullable=False))
    op.create_foreign_key(None, 'entreprises', 'entreprises', ['cree_par_entreprise_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entreprises', type_='foreignkey')
    op.drop_column('entreprises', 'actif')
    op.drop_column('entreprises', 'cree_par_entreprise_id')
    op.drop_column('entreprises', 'statut_fiche')
    postgresql.ENUM(name='statut_fiche').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_litiges_dossiers_facture_id'), table_name='litiges_dossiers')
    op.drop_table('litiges_dossiers')
    postgresql.ENUM(name='cause_litige').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='statut_litige').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
