"""cheque garantie et fiche acheteur minimale

Revision ID: aaeeb7b1336c
Revises: 92ee87d3254a
Create Date: 2026-09-05 19:08:18.336421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'aaeeb7b1336c'
down_revision: Union[str, None] = '92ee87d3254a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cheques_garantie',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facture_id', sa.UUID(), nullable=False),
    sa.Column('declare_par_utilisateur_id', sa.UUID(), nullable=True),
    sa.Column('numero_cheque', sa.String(length=50), nullable=False),
    sa.Column('banque_emettrice', sa.String(length=255), nullable=False),
    sa.Column('date_encaissement_prevue', sa.Date(), nullable=False),
    sa.Column('piece_jointe_url', sa.String(length=1024), nullable=False),
    sa.Column('statut', sa.Enum('DECLARE', 'CONFIRME_PAR_DONNEUR_ORDRE', 'REMIS_AU_PARTENAIRE', 'ENCAISSE', 'REJETE_SANS_PROVISION', name='statut_cheque_garantie'), nullable=False),
    sa.Column('date_remise_partenaire', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['declare_par_utilisateur_id'], ['utilisateurs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facture_id')
    )
    op.add_column('entreprises', sa.Column('contact_invitation_nom', sa.String(length=255), nullable=True))
    op.add_column('entreprises', sa.Column('contact_invitation_email', sa.String(length=255), nullable=True))
    op.add_column('entreprises', sa.Column('date_invitation_envoyee', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('entreprises', 'ninea',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('entreprises', 'secteur_activite',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('entreprises', 'date_creation',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('entreprises', 'contact_telephone',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('entreprises', 'contact_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('entreprises', 'adresse',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###

    # Non detecte par l'autogenerate (jamais le cas pour les valeurs d'enum Postgres) :
    # statut_facture stocke le .name (majuscules), sans values_callable.
    op.execute("ALTER TYPE statut_facture ADD VALUE IF NOT EXISTS 'EN_ATTENTE_KYC_ACHETEUR' BEFORE 'EMISE'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entreprises', 'adresse',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('entreprises', 'contact_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('entreprises', 'contact_telephone',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('entreprises', 'date_creation',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('entreprises', 'secteur_activite',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('entreprises', 'ninea',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('entreprises', 'date_invitation_envoyee')
    op.drop_column('entreprises', 'contact_invitation_email')
    op.drop_column('entreprises', 'contact_invitation_nom')
    op.drop_table('cheques_garantie')
    postgresql.ENUM(name='statut_cheque_garantie').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
