"""avoirs et creances compensation

Revision ID: bcfdd271d909
Revises: 1f151d0e24cf
Create Date: 2026-09-07 09:08:08.744347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'bcfdd271d909'
down_revision: Union[str, None] = '1f151d0e24cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avoirs_facture',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero_avoir', sa.String(length=100), nullable=False, comment='Sequence continue, sans trou, par PME — independante de numero_facture (voir app.services.numerotation_avoir).'),
    sa.Column('facture_id', sa.UUID(), nullable=False),
    sa.Column('montant_ht', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('montant_tva', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('montant_ttc', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('motif', sa.Enum('RETOUR_PARTIEL', 'ERREUR_PRIX', 'REMISE_COMMERCIALE', 'AUTRE', name='motif_avoir'), nullable=False),
    sa.Column('statut', sa.Enum('EMIS', 'CONFIRME_PAR_ACHETEUR', 'REJETE', name='statut_avoir'), nullable=False),
    sa.Column('date_emission', sa.Date(), nullable=False),
    sa.Column('piece_justificative_url', sa.String(length=1024), nullable=True),
    sa.Column('effet_applique', sa.String(length=30), nullable=True),
    sa.Column('montant_deduit_solde', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avoirs_facture_facture_id'), 'avoirs_facture', ['facture_id'], unique=False)
    op.create_index(op.f('ix_avoirs_facture_numero_avoir'), 'avoirs_facture', ['numero_avoir'], unique=False)
    op.create_table('creances_compensation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pme_id', sa.UUID(), nullable=False),
    sa.Column('avoir_id', sa.UUID(), nullable=False),
    sa.Column('montant_du', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('montant_recouvre', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'PARTIELLEMENT_RECOUVREE', 'SOLDEE', name='statut_creance'), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avoir_id'], ['avoirs_facture.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pme_id'], ['entreprises.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avoir_id')
    )
    op.create_index(op.f('ix_creances_compensation_pme_id'), 'creances_compensation', ['pme_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_creances_compensation_pme_id'), table_name='creances_compensation')
    op.drop_table('creances_compensation')
    op.drop_index(op.f('ix_avoirs_facture_numero_avoir'), table_name='avoirs_facture')
    op.drop_index(op.f('ix_avoirs_facture_facture_id'), table_name='avoirs_facture')
    op.drop_table('avoirs_facture')
    postgresql.ENUM(name='statut_creance').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='statut_avoir').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='motif_avoir').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
