"""forme juridique entreprise

Revision ID: c9b0a203e488
Revises: e36a04447684
Create Date: 2026-08-24 07:03:40.398530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9b0a203e488'
down_revision: Union[str, None] = 'e36a04447684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    forme_juridique_enum = sa.Enum(
        'personne_physique_entreprise_individuelle', 'gie', 'sarl', 'sa', 'autre', name='forme_juridique'
    )
    forme_juridique_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('entreprises', sa.Column('forme_juridique', forme_juridique_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entreprises', 'forme_juridique')
    sa.Enum(name='forme_juridique').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
