"""add motif_rejet_kyc

Revision ID: cca65c3ee78b
Revises: 2c2dc410e984
Create Date: 2026-08-23 16:54:56.185802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cca65c3ee78b'
down_revision: Union[str, None] = '2c2dc410e984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entreprises', sa.Column('motif_rejet_kyc', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entreprises', 'motif_rejet_kyc')
    # ### end Alembic commands ###
