"""invitations, validation role_validateur, utilisateur nom

Revision ID: e36a04447684
Revises: 85e01bbb0b02
Create Date: 2026-08-23 17:36:13.742238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36a04447684'
down_revision: Union[str, None] = '85e01bbb0b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('invite_par_id', sa.UUID(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invite_par_id'], ['utilisateurs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilisateur_id')
    )
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    op.add_column('utilisateurs', sa.Column('nom', sa.String(length=255), nullable=True))
    role_validateur_enum = sa.Enum('validateur_1', 'validateur_2', name='role_validateur')
    role_validateur_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('validations_facture', sa.Column('role_validateur', role_validateur_enum, nullable=False))
    op.drop_constraint('uq_validation_facture_ordre', 'validations_facture', type_='unique')
    op.create_unique_constraint('uq_validation_facture_role', 'validations_facture', ['facture_id', 'role_validateur'])
    op.drop_column('validations_facture', 'ordre_validation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validations_facture', sa.Column('ordre_validation', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_validation_facture_role', 'validations_facture', type_='unique')
    op.create_unique_constraint('uq_validation_facture_ordre', 'validations_facture', ['facture_id', 'ordre_validation'])
    op.drop_column('validations_facture', 'role_validateur')
    sa.Enum(name='role_validateur').drop(op.get_bind(), checkfirst=True)
    op.drop_column('utilisateurs', 'nom')
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.drop_table('invitations')
    # ### end Alembic commands ###
