"""facture brouillon avant transmission

Revision ID: eb6cbea0e3be
Revises: f3737a824497
Create Date: 2026-08-25 08:14:42.942434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb6cbea0e3be'
down_revision: Union[str, None] = 'f3737a824497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('factures', 'numero_facture',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               comment="Attribue par l'outil (jamais saisi) au moment de la transmission au donneur d'ordre ; absent tant que la facture est au statut brouillon.")
    # ### end Alembic commands ###

    # Non detecte par l'autogenerate (jamais le cas pour les valeurs d'enum Postgres) :
    # statut_facture stocke le .name (majuscules), sans values_callable.
    op.execute("ALTER TYPE statut_facture ADD VALUE IF NOT EXISTS 'BROUILLON' BEFORE 'EMISE'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('factures', 'numero_facture',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               comment=None,
               existing_comment="Attribue par l'outil (jamais saisi) au moment de la transmission au donneur d'ordre ; absent tant que la facture est au statut brouillon.")
    # ### end Alembic commands ###
